export const tokens = [
  {
    id: 1,
    name: 'Ethereum',
    symbol: 'ETH',
    icon: 'cryptocurrency-color:eth',
    logo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880',
    contract: '0x',
    balance: 2.34561,
  },
  {
    id: 2,
    name: 'Aavegotchi',
    symbol: 'GHST',
    icon: '',
    logo: 'https://assets.coingecko.com/coins/images/12467/small/ghst_200.png?1600750321',
    contract: '0x',
    balance: 20000,
  },
  {
    id: 3,
    name: 'MetaGame',
    symbol: 'SEED',
    icon: '',
    logo: 'https://assets.coingecko.com/coins/images/13099/small/V8phEz8V.png?1612854078',
  },
  {
    id: 4,
    name: 'Aave',
    symbol: 'AAVE',
    icon: 'cryptocurrency-color:aave',
    logo: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png?1601374110',
    contract: '0x',
    balance: 7.5,
  },
]
